
- name: Install NGINX
  ansible.builtin.package:
    name: "nginx"
    state: present

- name: configure
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Restar nginx
  ansible.builtin.service:
    name: "nginx"
    state: restarted
    enabled: true
